<?php
// don't load directly
defined( 'ABSPATH' ) || exit;

if ( ! class_exists( 'UACF7_icon' ) ) {
	class UACF7_icon extends UACF7_Fields {

		public function __construct( $field, $value = '', $settings_id = '', $parent_field = '', $section_key = '' ) {
			parent::__construct( $field, $value, $settings_id, $parent_field, $section_key  ); 
			//tf_icon_modal method load single time
			static $tf_icon_modal;
			if ( ! $tf_icon_modal ) {
				$tf_icon_modal = true;
				add_action( 'admin_footer', array( $this, 'tf_icon_modal' ) );
			}
		}

		public function render() {

			$default       = isset( $this->field['default'] ) ? $this->field['default'] : '';
			$value         = $this->value ? $this->value : '';
			$preview_class = $value ? 'tf-icon-preview' : 'tf-icon-preview tf-hide';
			$uniqueid      = uniqid();
			?>
            <div class="tf-icon-select" id="tf-icon-<?php echo esc_attr( $this->field['id'] . $uniqueid ); ?>">
                <div class="<?php echo esc_attr( $preview_class ); ?>">
                    <span class="tf-icon-preview-wrap tf-modal-btn">
                        <i class="<?php echo esc_attr( $value ); ?>"></i>
                    </span>
                    <span class="remove-icon">
                        <i class="ri-close-line"></i>
                    </span>
                </div>
                <a href="#" class="tf-admin-btn tf-modal-btn"><i class="ri-add-fill"></i><?php esc_html_e( 'Add Icon', 'ultimate-addons-cf7' ); ?></a>
                <input type="hidden" class="tf-icon-value" name="<?php echo esc_attr( $this->field_name() ); ?>" value="<?php echo esc_attr( $value ); ?>" <?php echo $this->field_attributes() ?>/>
            </div>
			<?php
		}

		public function tf_icon_modal() {
			?>
            <div class="tf-modal" id="tf-icon-modal" data-icon-field="">
                <div class="tf-modal-dialog">
                    <div class="container tf-modal-content">
                        <div class="tf-modal-header">
                            <div class="tf-icon-search">
                                <input type="text" placeholder="<?php esc_html_e( 'Search', 'ultimate-addons-cf7' ); ?>" class="tf-icon-search-input"/>
                            </div>
                            <a data-dismiss="modal" class="tf-modal-close">&#10005;</a>
                        </div>
                        <div class="tf-modal-body">
                            <div class="tf-icon-wrapper">
                                <ul class="tf-icon-tab-list">
									<?php
									$count     = 0;
									$icon_list = $this->get_icon_list();
									foreach ( $icon_list as $key => $value ) :
										if ( $value['icons'] ):
											?>
                                            <li class="tf-icon-tab <?php echo $count == 0 ? 'active' : '' ?>" data-tab="tf-icon-tab-<?php echo esc_attr( $key ) ?>">
                                                <i class="<?php echo esc_attr( $value['label_icon'] ) ?>"></i><?php echo esc_html( $value['label'] ); ?>
                                            </li>
										<?php
										endif;
										$count ++;
									endforeach; ?>
                                </ul>
                                <div class="tf-icon-tab-content">
									<?php
									$count     = 0;
									$icon_list = $this->get_icon_list();
									foreach ( $icon_list as $key => $value ) :
										?>
                                        <div class="tf-icon-tab-pane <?php echo $count == 0 ? 'active' : '' ?>" id="tf-icon-tab-<?php echo esc_attr( $key ) ?>">
                                            <ul class="tf-icon-list">
												<?php
												if ( $value['icons'] ):
													foreach ( $value['icons'] as $icon ) :
														?>
                                                        <li data-icon="<?php echo esc_attr( $icon ); ?>">
                                                            <div class="tf-icon-inner">
                                                                <i title="<?php echo esc_attr( $icon ); ?>" class="tf-main-icon <?php echo esc_attr( $icon ); ?>"></i>

                                                                <span class="check-icon">
                                                                    <i class="ri-check-line"></i>
                                                                </span>
                                                            </div>
                                                        </li>
													<?php endforeach;
												endif; ?>
                                            </ul>
                                        </div>
										<?php $count ++;
									endforeach; ?>
                                </div>
                            </div>
                        </div>
                        <div class="tf-modal-footer">
                            <a class="tf-icon-insert tf-admin-btn tf-btn-secondary disabled"><?php esc_html_e( 'Insert', 'ultimate-addons-cf7' ); ?></a>
                        </div>
                    </div>
                </div>
            </div>
			<?php
		}

		public function get_icon_list() {
			$icons = array(
				'fontawesome_6' => array(
					'label'      => __( 'Font Awesome 6', 'ultimate-addons-cf7' ),
					'label_icon' => 'fa-regular fa-font-awesome',
					'icons'      => $this->fontawesome_six_icons(),
				),
			);

			$icons = apply_filters( 'tf_icon_list', $icons );
			return $icons;
		}

		public function fontawesome_six_icons() {
			$icons = array(
				'fa-brands fa-monero',
				'fa-brands fa-hooli',
				'fa-brands fa-yelp',
				'fa-brands fa-cc-visa',
				'fa-brands fa-lastfm',
				'fa-brands fa-shopware',
				'fa-brands fa-creative-commons-nc',
				'fa-brands fa-aws',
				'fa-brands fa-redhat',
				'fa-brands fa-yoast',
				'fa-brands fa-cloudflare',
				'fa-brands fa-ups',
				'fa-brands fa-wpexplorer',
				'fa-brands fa-dyalog',
				'fa-brands fa-bity',
				'fa-brands fa-stackpath',
				'fa-brands fa-buysellads',
				'fa-brands fa-first-order',
				'fa-brands fa-modx',
				'fa-brands fa-guilded',
				'fa-brands fa-vnv',
				'fa-brands fa-square-js',
				'fa-brands fa-js-square',
				'fa-brands fa-microsoft',
				'fa-brands fa-qq',
				'fa-brands fa-orcid',
				'fa-brands fa-java',
				'fa-brands fa-invision',
				'fa-brands fa-creative-commons-pd-alt',
				'fa-brands fa-centercode',
				'fa-brands fa-glide-g',
				'fa-brands fa-drupal',
				'fa-brands fa-hire-a-helper',
				'fa-brands fa-creative-commons-by',
				'fa-brands fa-unity',
				'fa-brands fa-whmcs',
				'fa-brands fa-rocketchat',
				'fa-brands fa-vk',
				'fa-brands fa-untappd',
				'fa-brands fa-mailchimp',
				'fa-brands fa-css3-alt',
				'fa-brands fa-square-reddit',
				'fa-brands fa-reddit-square',
				'fa-brands fa-vimeo-v',
				'fa-brands fa-contao',
				'fa-brands fa-square-font-awesome',
				'fa-brands fa-deskpro',
				'fa-brands fa-sistrix',
				'fa-brands fa-square-instagram',
				'fa-brands fa-instagram-square',
				'fa-brands fa-battle-net',
				'fa-brands fa-the-red-yeti',
				'fa-brands fa-square-hacker-news',
				'fa-brands fa-hacker-news-square',
				'fa-brands fa-edge',
				'fa-brands fa-napster',
				'fa-brands fa-square-snapchat',
				'fa-brands fa-snapchat-square',
				'fa-brands fa-google-plus-g',
				'fa-brands fa-artstation',
				'fa-brands fa-markdown',
				'fa-brands fa-sourcetree',
				'fa-brands fa-google-plus',
				'fa-brands fa-diaspora',
				'fa-brands fa-foursquare',
				'fa-brands fa-stack-overflow',
				'fa-brands fa-github-alt',
				'fa-brands fa-phoenix-squadron',
				'fa-brands fa-pagelines',
				'fa-brands fa-algolia',
				'fa-brands fa-red-river',
				'fa-brands fa-creative-commons-sa',
				'fa-brands fa-safari',
				'fa-brands fa-google',
				'fa-brands fa-square-font-awesome-stroke',
				'fa-brands fa-font-awesome-alt',
				'fa-brands fa-atlassian',
				'fa-brands fa-linkedin-in',
				'fa-brands fa-digital-ocean',
				'fa-brands fa-nimblr',
				'fa-brands fa-chromecast',
				'fa-brands fa-evernote',
				'fa-brands fa-hacker-news',
				'fa-brands fa-creative-commons-sampling',
				'fa-brands fa-adversal',
				'fa-brands fa-creative-commons',
				'fa-brands fa-watchman-monitoring',
				'fa-brands fa-fonticons',
				'fa-brands fa-weixin',
				'fa-brands fa-shirtsinbulk',
				'fa-brands fa-codepen',
				'fa-brands fa-git-alt',
				'fa-brands fa-lyft',
				'fa-brands fa-rev',
				'fa-brands fa-windows',
				'fa-brands fa-wizards-of-the-coast',
				'fa-brands fa-square-viadeo',
				'fa-brands fa-viadeo-square',
				'fa-brands fa-meetup',
				'fa-brands fa-centos',
				'fa-brands fa-adn',
				'fa-brands fa-cloudsmith',
				'fa-brands fa-pied-piper-alt',
				'fa-brands fa-square-dribbble',
				'fa-brands fa-dribbble-square',
				'fa-brands fa-codiepie',
				'fa-brands fa-node',
				'fa-brands fa-mix',
				'fa-brands fa-steam',
				'fa-brands fa-cc-apple-pay',
				'fa-brands fa-scribd',
				'fa-brands fa-openid',
				'fa-brands fa-instalod',
				'fa-brands fa-expeditedssl',
				'fa-brands fa-sellcast',
				'fa-brands fa-square-twitter',
				'fa-brands fa-twitter-square',
				'fa-brands fa-r-project',
				'fa-brands fa-delicious',
				'fa-brands fa-freebsd',
				'fa-brands fa-vuejs',
				'fa-brands fa-accusoft',
				'fa-brands fa-ioxhost',
				'fa-brands fa-fonticons-fi',
				'fa-brands fa-app-store',
				'fa-brands fa-cc-mastercard',
				'fa-brands fa-itunes-note',
				'fa-brands fa-golang',
				'fa-brands fa-kickstarter',
				'fa-brands fa-grav',
				'fa-brands fa-weibo',
				'fa-brands fa-uncharted',
				'fa-brands fa-firstdraft',
				'fa-brands fa-square-youtube',
				'fa-brands fa-youtube-square',
				'fa-brands fa-wikipedia-w',
				'fa-brands fa-wpressr',
				'fa-brands fa-rendact',
				'fa-brands fa-angellist',
				'fa-brands fa-galactic-republic',
				'fa-brands fa-nfc-directional',
				'fa-brands fa-skype',
				'fa-brands fa-joget',
				'fa-brands fa-fedora',
				'fa-brands fa-stripe-s',
				'fa-brands fa-meta',
				'fa-brands fa-laravel',
				'fa-brands fa-hotjar',
				'fa-brands fa-bluetooth-b',
				'fa-brands fa-sticker-mule',
				'fa-brands fa-creative-commons-zero',
				'fa-brands fa-hips',
				'fa-brands fa-behance',
				'fa-brands fa-reddit',
				'fa-brands fa-discord',
				'fa-brands fa-chrome',
				'fa-brands fa-app-store-ios',
				'fa-brands fa-cc-discover',
				'fa-brands fa-wpbeginner',
				'fa-brands fa-confluence',
				'fa-brands fa-mdb',
				'fa-brands fa-dochub',
				'fa-brands fa-accessible-icon',
				'fa-brands fa-ebay',
				'fa-brands fa-amazon',
				'fa-brands fa-unsplash',
				'fa-brands fa-yarn',
				'fa-brands fa-square-steam',
				'fa-brands fa-steam-square',
				'fa-brands fa-500px',
				'fa-brands fa-square-vimeo',
				'fa-brands fa-vimeo-square',
				'fa-brands fa-asymmetrik',
				'fa-brands fa-font-awesome',
				'fa-brands fa-font-awesome-flag',
				'fa-brands fa-font-awesome-logo-full',
				'fa-brands fa-gratipay',
				'fa-brands fa-apple',
				'fa-brands fa-hive',
				'fa-brands fa-gitkraken',
				'fa-brands fa-keybase',
				'fa-brands fa-apple-pay',
				'fa-brands fa-padlet',
				'fa-brands fa-amazon-pay',
				'fa-brands fa-square-github',
				'fa-brands fa-github-square',
				'fa-brands fa-stumbleupon',
				'fa-brands fa-fedex',
				'fa-brands fa-phoenix-framework',
				'fa-brands fa-shopify',
				'fa-brands fa-neos',
				'fa-brands fa-hackerrank',
				'fa-brands fa-researchgate',
				'fa-brands fa-swift',
				'fa-brands fa-angular',
				'fa-brands fa-speakap',
				'fa-brands fa-angrycreative',
				'fa-brands fa-y-combinator',
				'fa-brands fa-empire',
				'fa-brands fa-envira',
				'fa-brands fa-square-gitlab',
				'fa-brands fa-gitlab-square',
				'fa-brands fa-studiovinari',
				'fa-brands fa-pied-piper',
				'fa-brands fa-wordpress',
				'fa-brands fa-product-hunt',
				'fa-brands fa-firefox',
				'fa-brands fa-linode',
				'fa-brands fa-goodreads',
				'fa-brands fa-square-odnoklassniki',
				'fa-brands fa-odnoklassniki-square',
				'fa-brands fa-jsfiddle',
				'fa-brands fa-sith',
				'fa-brands fa-themeisle',
				'fa-brands fa-page4',
				'fa-brands fa-hashnode',
				'fa-brands fa-react',
				'fa-brands fa-cc-paypal',
				'fa-brands fa-squarespace',
				'fa-brands fa-cc-stripe',
				'fa-brands fa-creative-commons-share',
				'fa-brands fa-bitcoin',
				'fa-brands fa-keycdn',
				'fa-brands fa-opera',
				'fa-brands fa-itch-io',
				'fa-brands fa-umbraco',
				'fa-brands fa-galactic-senate',
				'fa-brands fa-ubuntu',
				'fa-brands fa-draft2digital',
				'fa-brands fa-stripe',
				'fa-brands fa-houzz',
				'fa-brands fa-gg',
				'fa-brands fa-dhl',
				'fa-brands fa-square-pinterest',
				'fa-brands fa-pinterest-square',
				'fa-brands fa-xing',
				'fa-brands fa-blackberry',
				'fa-brands fa-creative-commons-pd',
				'fa-brands fa-playstation',
				'fa-brands fa-quinscape',
				'fa-brands fa-less',
				'fa-brands fa-blogger-b',
				'fa-brands fa-opencart',
				'fa-brands fa-vine',
				'fa-brands fa-paypal',
				'fa-brands fa-gitlab',
				'fa-brands fa-typo3',
				'fa-brands fa-reddit-alien',
				'fa-brands fa-yahoo',
				'fa-brands fa-dailymotion',
				'fa-brands fa-affiliatetheme',
				'fa-brands fa-pied-piper-pp',
				'fa-brands fa-bootstrap',
				'fa-brands fa-odnoklassniki',
				'fa-brands fa-nfc-symbol',
				'fa-brands fa-ethereum',
				'fa-brands fa-speaker-deck',
				'fa-brands fa-creative-commons-nc-eu',
				'fa-brands fa-patreon',
				'fa-brands fa-avianex',
				'fa-brands fa-ello',
				'fa-brands fa-gofore',
				'fa-brands fa-bimobject',
				'fa-brands fa-facebook-f',
				'fa-brands fa-square-google-plus',
				'fa-brands fa-google-plus-square',
				'fa-brands fa-mandalorian',
				'fa-brands fa-first-order-alt',
				'fa-brands fa-osi',
				'fa-brands fa-google-wallet',
				'fa-brands fa-d-and-d-beyond',
				'fa-brands fa-periscope',
				'fa-brands fa-fulcrum',
				'fa-brands fa-cloudscale',
				'fa-brands fa-forumbee',
				'fa-brands fa-mizuni',
				'fa-brands fa-schlix',
				'fa-brands fa-square-xing',
				'fa-brands fa-xing-square',
				'fa-brands fa-bandcamp',
				'fa-brands fa-wpforms',
				'fa-brands fa-cloudversify',
				'fa-brands fa-usps',
				'fa-brands fa-megaport',
				'fa-brands fa-magento',
				'fa-brands fa-spotify',
				'fa-brands fa-optin-monster',
				'fa-brands fa-fly',
				'fa-brands fa-aviato',
				'fa-brands fa-itunes',
				'fa-brands fa-cuttlefish',
				'fa-brands fa-blogger',
				'fa-brands fa-flickr',
				'fa-brands fa-viber',
				'fa-brands fa-soundcloud',
				'fa-brands fa-digg',
				'fa-brands fa-tencent-weibo',
				'fa-brands fa-symfony',
				'fa-brands fa-maxcdn',
				'fa-brands fa-etsy',
				'fa-brands fa-facebook-messenger',
				'fa-brands fa-audible',
				'fa-brands fa-think-peaks',
				'fa-brands fa-bilibili',
				'fa-brands fa-erlang',
				'fa-brands fa-cotton-bureau',
				'fa-brands fa-dashcube',
				'fa-brands fa-42-group',
				'fa-brands fa-innosoft',
				'fa-brands fa-stack-exchange',
				'fa-brands fa-elementor',
				'fa-brands fa-square-pied-piper',
				'fa-brands fa-pied-piper-square',
				'fa-brands fa-creative-commons-nd',
				'fa-brands fa-palfed',
				'fa-brands fa-superpowers',
				'fa-brands fa-resolving',
				'fa-brands fa-xbox',
				'fa-brands fa-searchengin',
				'fa-brands fa-tiktok',
				'fa-brands fa-square-facebook',
				'fa-brands fa-facebook-square',
				'fa-brands fa-renren',
				'fa-brands fa-linux',
				'fa-brands fa-glide',
				'fa-brands fa-linkedin',
				'fa-brands fa-hubspot',
				'fa-brands fa-deploydog',
				'fa-brands fa-twitch',
				'fa-brands fa-ravelry',
				'fa-brands fa-mixer',
				'fa-brands fa-square-lastfm',
				'fa-brands fa-lastfm-square',
				'fa-brands fa-vimeo',
				'fa-brands fa-mendeley',
				'fa-brands fa-uniregistry',
				'fa-brands fa-figma',
				'fa-brands fa-creative-commons-remix',
				'fa-brands fa-cc-amazon-pay',
				'fa-brands fa-dropbox',
				'fa-brands fa-instagram',
				'fa-brands fa-cmplid',
				'fa-brands fa-facebook',
				'fa-brands fa-gripfire',
				'fa-brands fa-jedi-order',
				'fa-brands fa-uikit',
				'fa-brands fa-fort-awesome-alt',
				'fa-brands fa-phabricator',
				'fa-brands fa-ussunnah',
				'fa-brands fa-earlybirds',
				'fa-brands fa-trade-federation',
				'fa-brands fa-autoprefixer',
				'fa-brands fa-whatsapp',
				'fa-brands fa-slideshare',
				'fa-brands fa-google-play',
				'fa-brands fa-viadeo',
				'fa-brands fa-line',
				'fa-brands fa-google-drive',
				'fa-brands fa-servicestack',
				'fa-brands fa-simplybuilt',
				'fa-brands fa-bitbucket',
				'fa-brands fa-imdb',
				'fa-brands fa-deezer',
				'fa-brands fa-raspberry-pi',
				'fa-brands fa-jira',
				'fa-brands fa-docker',
				'fa-brands fa-screenpal',
				'fa-brands fa-bluetooth',
				'fa-brands fa-gitter',
				'fa-brands fa-d-and-d',
				'fa-brands fa-microblog',
				'fa-brands fa-cc-diners-club',
				'fa-brands fa-gg-circle',
				'fa-brands fa-pied-piper-hat',
				'fa-brands fa-kickstarter-k',
				'fa-brands fa-yandex',
				'fa-brands fa-readme',
				'fa-brands fa-html5',
				'fa-brands fa-sellsy',
				'fa-brands fa-sass',
				'fa-brands fa-wirsindhandwerk',
				'fa-brands fa-wsh',
				'fa-brands fa-buromobelexperte',
				'fa-brands fa-salesforce',
				'fa-brands fa-octopus-deploy',
				'fa-brands fa-medapps',
				'fa-brands fa-ns8',
				'fa-brands fa-pinterest-p',
				'fa-brands fa-apper',
				'fa-brands fa-fort-awesome',
				'fa-brands fa-waze',
				'fa-brands fa-cc-jcb',
				'fa-brands fa-snapchat',
				'fa-brands fa-snapchat-ghost',
				'fa-brands fa-fantasy-flight-games',
				'fa-brands fa-rust',
				'fa-brands fa-wix',
				'fa-brands fa-square-behance',
				'fa-brands fa-behance-square',
				'fa-brands fa-supple',
				'fa-brands fa-rebel',
				'fa-brands fa-css3',
				'fa-brands fa-staylinked',
				'fa-brands fa-kaggle',
				'fa-brands fa-space-awesome',
				'fa-brands fa-deviantart',
				'fa-brands fa-cpanel',
				'fa-brands fa-goodreads-g',
				'fa-brands fa-square-git',
				'fa-brands fa-git-square',
				'fa-brands fa-square-tumblr',
				'fa-brands fa-tumblr-square',
				'fa-brands fa-trello',
				'fa-brands fa-creative-commons-nc-jp',
				'fa-brands fa-get-pocket',
				'fa-brands fa-perbyte',
				'fa-brands fa-grunt',
				'fa-brands fa-weebly',
				'fa-brands fa-connectdevelop',
				'fa-brands fa-leanpub',
				'fa-brands fa-black-tie',
				'fa-brands fa-themeco',
				'fa-brands fa-python',
				'fa-brands fa-android',
				'fa-brands fa-bots',
				'fa-brands fa-free-code-camp',
				'fa-brands fa-hornbill',
				'fa-brands fa-js',
				'fa-brands fa-ideal',
				'fa-brands fa-git',
				'fa-brands fa-dev',
				'fa-brands fa-sketch',
				'fa-brands fa-yandex-international',
				'fa-brands fa-cc-amex',
				'fa-brands fa-uber',
				'fa-brands fa-github',
				'fa-brands fa-php',
				'fa-brands fa-alipay',
				'fa-brands fa-youtube',
				'fa-brands fa-skyatlas',
				'fa-brands fa-firefox-browser',
				'fa-brands fa-replyd',
				'fa-brands fa-suse',
				'fa-brands fa-jenkins',
				'fa-brands fa-twitter',
				'fa-brands fa-rockrms',
				'fa-brands fa-pinterest',
				'fa-brands fa-buffer',
				'fa-brands fa-npm',
				'fa-brands fa-yammer',
				'fa-brands fa-btc',
				'fa-brands fa-dribbble',
				'fa-brands fa-stumbleupon-circle',
				'fa-brands fa-internet-explorer',
				'fa-brands fa-telegram',
				'fa-brands fa-telegram-plane',
				'fa-brands fa-old-republic',
				'fa-brands fa-square-whatsapp',
				'fa-brands fa-whatsapp-square',
				'fa-brands fa-node-js',
				'fa-brands fa-edge-legacy',
				'fa-brands fa-slack',
				'fa-brands fa-slack-hash',
				'fa-brands fa-medrt',
				'fa-brands fa-usb',
				'fa-brands fa-tumblr',
				'fa-brands fa-vaadin',
				'fa-brands fa-quora',
				'fa-brands fa-reacteurope',
				'fa-brands fa-medium',
				'fa-brands fa-medium-m',
				'fa-brands fa-amilia',
				'fa-brands fa-mixcloud',
				'fa-brands fa-flipboard',
				'fa-brands fa-viacoin',
				'fa-brands fa-critical-role',
				'fa-brands fa-sitrox',
				'fa-brands fa-discourse',
				'fa-brands fa-joomla',
				'fa-brands fa-mastodon',
				'fa-brands fa-airbnb',
				'fa-brands fa-wolf-pack-battalion',
				'fa-brands fa-buy-n-large',
				'fa-brands fa-gulp',
				'fa-brands fa-creative-commons-sampling-plus',
				'fa-brands fa-strava',
				'fa-brands fa-ember',
				'fa-brands fa-canadian-maple-leaf',
				'fa-brands fa-teamspeak',
				'fa-brands fa-pushed',
				'fa-brands fa-wordpress-simple',
				'fa-brands fa-nutritionix',
				'fa-brands fa-wodu',
				'fa-brands fa-google-pay',
				'fa-brands fa-intercom',
				'fa-brands fa-zhihu',
				'fa-brands fa-korvue',
				'fa-brands fa-pix',
				'fa-brands fa-steam-symbol',
			);
			return $icons;
		}
	}
}